### ISSUE TITLE
训练效果怎么样

### ISSUE THREAD

**Issue by Curious-chen** [l294265421/alpaca-rlhf#1]
作者，你好，进行RLHF后，模型效果怎么样的，在什么方面上会有提升？

**Comment by l294265421** [comment]
> 作者，你好，进行RLHF后，模型效果怎么样的，在什么方面上会有提升？

现在只是简单测试一下，从测试的例子看，RLHF训练之后，模型的输出似乎更符合人的偏好了；但大部分情况下，针对一些简单的问题，没有变化。下面是两个例子（为了方便对比，解码用的贪心搜索）：

示例一：RLHF训练后，对人的意图理解更为准确
flhf前：
![图片](https://user-images.githubusercontent.com/9948265/236762265-4cd0dfc4-51e1-476c-ba4d-af74436ca610.png)

flhf后：
![图片](https://user-images.githubusercontent.com/9948265/236762324-2119e900-a777-467d-9a09-0554ac08e947.png)

示例二：输出一样
flhf前：
![图片](https://user-images.githubusercontent.com/9948265/236762159-55b06f64-0eaa-4967-a7a1-1c345c6dffc3.png)

flhf后：
![图片](https://user-images.githubusercontent.com/9948265/236762212-aadfad88-c4f4-4d9e-8a91-4dba53bb53d1.png)

从目前训练过程的reward等指标来看，还有很大的优化空间。不过，以现在的资源直接调LLaMA 7b，迭代很慢，正在切换回小一些的模型去实验，比如opt 1.3b。

**Comment by l294265421** [comment]
> 作者，你好，进行RLHF后，模型效果怎么样的，在什么方面上会有提升？

优化了训练，RLHF训练的模型回答看起来更丰富一些，见readme

**Comment by l294265421** [comment]
> 作者，你好，进行RLHF后，模型效果怎么样的，在什么方面上会有提升？

在readme里加了STF和RLHF模型的在线demo，可以直接体验对比
